---

- name: Create AWX schedules
  awx.awx.application:
    controller_host: "{{ tower_awx[awx_type][awx_env]['url'] }}"
    controller_username: "{{ tower_awx[awx_type][awx_env]['api_user'] if awx_token is undefined else omit }}"
    controller_password: "{{ tower_awx[awx_type][awx_env]['api_password'] if awx_token is undefined else omit }}"
    controller_oauthtoken: "{{ awx_token | default(omit) }}"
    validate_certs: "{{ tower_awx[awx_type][awx_env]['validate_certs'] }}"

    name: "{{ item.name }}"
    state: "{{ item.state | default(omit) }}"
    description: "{{ item.description | default(omit) }}"

    authorization_grant_type: "{{ item.authorization_grant_type | default(omit) }}"
    client_type: "{{ item.client_type | default(omit) }}"
    redirect_uris: "{{ item.redirect_uris | default(omit) }}"
    skip_authorization: "{{ item.skip_authorization | default(omit) }}"

  # ignore_errors: yes
  loop: "{{ lookup('file', awx_config_path + '/applications/applications.yml') | from_yaml }}"
  loop_control:
    label:
      - "{{ item.name }}"
