---

- name: Create AWX schedules
  awx.awx.application:
    controller_host: "{{ awx_url }}"
    controller_username: "{{ awx_username if awx_token is undefined else omit }}"
    controller_password: "{{ awx_password if awx_token is undefined else omit }}"
    controller_oauthtoken: "{{ awx_token | default(omit) }}"
    validate_certs: "{{ awx_verify_ssl }}"

    name: "{{ item.name }}"
    state: "{{ item.state | default(omit) }}"
    description: "{{ item.description | default(omit) }}"

    authorization_grant_type: "{{ item.authorization_grant_type | default(omit) }}"
    client_type: "{{ item.client_type | default(omit) }}"
    redirect_uris: "{{ item.redirect_uris | default(omit) }}"
    skip_authorization: "{{ item.skip_authorization | default(omit) }}"

  # ignore_errors: yes
  loop: "{{ lookup('file', awx_config_path + '/applications/applications.yml') | from_yaml }}"
  loop_control:
    label:
      - "{{ item.name }}"
