---

- name: Create AWX application
  awx.awx.application:

    # AWX connection & authentication
    controller_config_file: "{{ awx_config_file | default(omit) }}"
    controller_host: "{{ awx_url }}"
    controller_username: "{{ awx_username if awx_token is undefined else omit }}"
    controller_password: "{{ awx_password if awx_token is undefined else omit }}"
    controller_oauthtoken: "{{ awx_token | default(omit) }}"
    validate_certs: "{{ awx_verify_ssl }}"

    # Required parameters
    name: "{{ item.name }}"
    organization: "{{ item.organization }}"

    # Optional parameters
    authorization_grant_type: "{{ item.authorization_grant_type | default(omit) }}"
    client_type: "{{ item.client_type | default(omit) }}"
    description: "{{ item.description | default(omit) }}"
    new_name: "{{ item.new_name | default(omit) }}"
    redirect_uris: "{{ item.redirect_uris | default(omit) }}"
    skip_authorization: "{{ item.skip_authorization | default(omit) }}"
    state: "{{ item.state | default(omit) }}"

  ignore_errors: "{{ awx_ignore_errors | default(False) }}"  # noqa ignore-errors
  loop: "{{ lookup('file', awx_config_path + '/applications/applications.yml') | from_yaml }}"
  loop_control:
    label: "{{ item.name }}"
