---

- name: Create AWX credential
  awx.awx.credential:

    # AWX connection & authentication
    controller_config_file: "{{ awx_config_file | default(omit) }}"
    controller_host: "{{ awx_url }}"
    controller_username: "{{ awx_username if awx_token is undefined else omit }}"
    controller_password: "{{ awx_password if awx_token is undefined else omit }}"
    controller_oauthtoken: "{{ awx_token | default(omit) }}"
    validate_certs: "{{ awx_verify_ssl }}"

    # Required parameters
    credential_type: "{{ item.credential_type }}"
    name: "{{ item.name }}"
    organization: "{{ item.organization }}"

    # Optional parameters
    copy_from: "{{ item.copy_from | default(omit) }}"
    description: "{{ item.description | default(omit) }}"
    inputs: "{{ item.inputs if item.inputs is defined else (lookup('file', awx_config_path + '/credentials/inputs/' + item.name + '.json', errors='ignore') | default({}, True)) }}"
    new_name: "{{ item.new_name | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    team: "{{ item.team | default(omit) }}"
    update_secrets: "{{ item.update_secrets | default(False) }}"
    user: "{{ item.user | default(omit) }}"

  ignore_errors: "{{ awx_ignore_errors | default(False) }}"  # noqa ignore-errors
  loop: "{{ lookup('template', awx_config_path + '/credentials/credentials.yml') | from_yaml }}"
  loop_control:
    label: "{{ item.name }}"
