---

- name: Create AWX credential_type
  awx.awx.credential_type:

    # AWX connection & authentication
    controller_config_file: "{{ awx_config_file | default(omit) }}"
    controller_host: "{{ awx_url }}"
    controller_username: "{{ awx_username if awx_token is undefined else omit }}"
    controller_password: "{{ awx_password if awx_token is undefined else omit }}"
    controller_oauthtoken: "{{ awx_token | default(omit) }}"
    validate_certs: "{{ awx_verify_ssl }}"

    # Required parameters
    kind: "{{ item.kind }}"
    name: "{{ item.name }}"

    # Optional parameters
    description: "{{ item.description | default(omit) }}"
    injectors: "{{ lookup('file', awx_config_path + '/credential_types/injectors/' + item.name + '.json') | default({}, True) }}"
    inputs: "{{ lookup('file', awx_config_path + '/credential_types/inputs/' + item.name + '.json') | default({}, True) }}"
    new_name: "{{ item.new_name | default(omit) }}"
    state: "{{ item.state | default(omit) }}"

  ignore_errors: "{{ ignore_errors | default(False) }}"  # noqa ignore-errors
  loop: "{{ lookup('file', awx_config_path + '/credential_types/credential_types.yml') | from_yaml }}"
  loop_control:
    label: "{{ item.name }}"
