---

- name: Create AWX credential types  # noqa ignore-errors
  awx.awx.credential_type:
    controller_host: "{{ awx_url }}"
    controller_username: "{{ awx_username if awx_token is undefined else omit }}"
    controller_password: "{{ awx_password if awx_token is undefined else omit }}"
    controller_oauthtoken: "{{ awx_token | default(omit) }}"
    validate_certs: "{{ awx_verify_ssl }}"

    name: "{{ item.name }}"
    kind: "{{ item.kind }}"
    description: "{{ item.description }}"
    injectors: "{{ lookup('file', awx_config_path + '/credential_types/injectors/' + item.name + '.json') }}"
    inputs: "{{ lookup('file', awx_config_path + '/credential_types/inputs/' + item.name + '.json') }}"

  # ignore_errors: yes
  loop: "{{ lookup('file', awx_config_path + '/credential_types/credential_types.yml') | from_yaml }}"
  loop_control:
    label:
      - "{{ item.name }}"
