---

- name: Create AWX credentials  # noqa ignore-errors
  awx.awx.credential:
    controller_host: "{{ awx_url }}"
    controller_username: "{{ awx_username if awx_token is undefined else omit }}"
    controller_password: "{{ awx_password if awx_token is undefined else omit }}"
    controller_oauthtoken: "{{ awx_token | default(omit) }}"
    validate_certs: "{{ awx_verify_ssl }}"

    name: "{{ item.name }}"
    organization: "{{ item.organization }}"

    description: "{{ item.description | default(omit) }}"
    credential_type: "{{ item.credential_type }}"
    inputs: "{{ item.inputs | default(omit) }}"
    update_secrets: "{{ item.update_secret | default(False) }}"

  # ignore_errors: yes
  # loop: "{{ lookup('file', awx_config_path + '/credentials/credentials.yml') | from_yaml }}"
  loop: "{{ lookup('template', awx_config_path + '/credentials/credentials.yml') | from_yaml }}"
  loop_control:
    label:
      - "{{ item.name }}"
