---

- name: Create AWX credential_type  # noqa jinja[spacing]
  awx.awx.credential_type:

    # AWX connection & authentication
    controller_config_file: "{{ awx_config_file | default(omit) }}"
    controller_host: "{{ awx_url }}"
    controller_username: "{{ awx_username if awx_token is undefined else omit }}"
    controller_password: "{{ awx_password if awx_token is undefined else omit }}"
    controller_oauthtoken: "{{ awx_token | default(omit) }}"
    validate_certs: "{{ awx_verify_ssl }}"

    # Required parameters
    kind: "{{ item.kind }}"
    name: "{{ item.name }}"

    # Optional parameters
    description: "{{ item.description | default(omit) }}"
    injectors: >-
      {%- if item.injectors is defined -%}
      {{ item.injectors }}
      {%- else -%}
      {%- set var_path = '/credential_types/injectors/' -%}
      {%- if awx_inputs_format == 'json' -%}
      {%- set varsfile = awx_config_path + var_path + item.name + '.json' -%}
      {{ lookup('file', varsfile, errors='ignore') | default({}, true) }}
      {%- elif awx_inputs_format == 'yaml' -%}
      {%- set varsfile = awx_config_path + var_path + item.name + '.yml' -%}
      {{ lookup('file', varsfile, errors='ignore') | from_yaml | default({}, true) }}
      {%- endif -%}
      {%- endif -%}
    inputs: >-
      {%- if item.inputs is defined -%}
      {{ item.inputs }}
      {%- else -%}
      {%- set var_path = '/credential_types/inputs/' -%}
      {%- if awx_inputs_format == 'json' -%}
      {%- set varsfile = awx_config_path + var_path + item.name + '.json' -%}
      {{ lookup('file', varsfile, errors='ignore') | default({}, true) }}
      {%- elif awx_inputs_format == 'yaml' -%}
      {%- set varsfile = awx_config_path + var_path + item.name + '.yml' -%}
      {{ lookup('file', varsfile, errors='ignore') | from_yaml | default({}, true) }}
      {%- endif -%}
      {%- endif -%}
    new_name: "{{ item.new_name | default(omit) }}"
    state: "{{ item.state | default(omit) }}"

  ignore_errors: "{{ awx_ignore_errors | default(False) }}"  # noqa ignore-errors
  loop: "{{ lookup('file', awx_config_path + '/credential_types/credential_types.yml') | from_yaml }}"
  loop_control:
    label: "{{ item.name }}"
