---

- name: Render extra-vars from template
  ansible.builtin.template:
    src: "{{ template_in }}"
    dest: "{{ file_out }}"
    mode: "0644"
    block_start_string: "{{ awx_casc_template_block_start_string | default(omit) }}"
    block_end_string: "{{ awx_casc_template_block_end_string | default(omit) }}"
    comment_start_string: "{{ awx_casc_template_comment_start_string | default(omit) }}"
    comment_end_string: "{{ awx_casc_template_comment_end_string | default(omit) }}"
    variable_start_string: "{{ awx_casc_template_variable_start_string | default(omit) }}"
    variable_end_string: "{{ awx_casc_template_variable_end_string | default(omit) }}"
  vars:
    template_in: "{{ awx_config_path + '/' + awx_resource + '/extra_vars/' + item.name + '.yml.j2' }}"
    file_out: "/tmp/ev-{{ item.name }}.yml"
  changed_when: false
  when:
    - (item.state | default('present')) == 'present'
    - template_in is is_file
  delegate_to: localhost
  loop: "{{ lookup('vars', '__awx_' + awx_resource) }}"
  loop_control:
    label: "{{ item.name }}"

- name: Create extra-vars files  # noqa jinja[spacing]
  ansible.builtin.copy:
    content: >
      {%- if item.extra_vars is defined -%}
      {%- set extra_vars = item.extra_vars -%}
      {%- else -%}
      {%- set var_path = '/' + awx_resource + '/extra_vars/' -%}
      {%- if awx_vars_format == 'json' -%}
      {%- set varsfile = awx_config_path + var_path + item.name + '.json' -%}
      {%- set extra_vars = lookup('file', varsfile, errors='ignore') | default({}, true) -%}
      {%- elif awx_vars_format == 'yaml' -%}
      {%- set varsfile = awx_config_path + var_path + item.name + '.yml' -%}
      {%- set extra_vars = lookup('file', varsfile, errors='ignore') | from_yaml | default({}, true) -%}
      {%- endif -%}
      {%- endif -%}
      {%- if extra_vars == {} -%}
      ---
      {%- else -%}
      {{ extra_vars | to_nice_yaml(indent=2, explicit_start=True) }}
      {%- endif -%}
    dest: "{{ file_out }}"
    mode: "0640"
  vars:
    template_in: "{{ awx_config_path + '/' + awx_resource + '/extra_vars/' + item.name + '.yml.j2' }}"
    file_in: "{{ awx_config_path + '/' + awx_resource + '/extra_vars/' + item.name + '.yml' }}"
    file_out: "/tmp/ev-{{ item.name }}.yml"
  when:
    - (item.state | default('present')) == 'present'
    - template_in is not is_file
  changed_when: false
  ignore_errors: "{{ awx_ignore_errors | default(False) }}"  # noqa ignore-errors
  delegate_to: localhost
  loop: "{{ lookup('vars', '__awx_' + awx_resource) }}"
  loop_control:
    label: "{{ item.name }}"
