---

- name: Create AWX groups  # noqa jinja[spacing]
  awx.awx.group:

    # AWX connection & authentication
    controller_config_file: "{{ awx_config_file | default(omit) }}"
    controller_host: "{{ awx_url }}"
    controller_username: "{{ awx_username if awx_token is undefined else omit }}"
    controller_password: "{{ awx_password if awx_token is undefined else omit }}"
    controller_oauthtoken: "{{ awx_token | default(omit) }}"
    validate_certs: "{{ awx_verify_ssl }}"

    # Required parameters
    inventory: "{{ item.inventory }}"
    name: "{{ item.name }}"

    # Optional parameters
    children: "{{ item.children | default([]) }}"
    description: "{{ item.description | default(omit) }}"
    hosts: >-
      {%- if awx_casc_skip_hosts | bool -%}
      []
      {%- else -%}
      {{ item.hosts | default([]) | difference(awx_hosts_non_existing) }}
      {%- endif -%}
    new_name: "{{ item.new_name | default(omit) }}"
    preserve_existing_children: "{{ item.preserve_existing_children | default(omit) }}"
    preserve_existing_hosts: "{{ item.preserve_existing_hosts | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    variables: >-
      {%- set var_path = '/groups/variables/' -%}
      {%- if awx_vars_format == 'json' -%}
      {%- set varsfile = awx_config_path + var_path + item.name + '.json' -%}
      {{ lookup('file', varsfile, errors='ignore') | default({}, true) }}
      {%- elif awx_vars_format == 'yaml' -%}
      {%- set varsfile = awx_config_path + var_path + item.name + '.yml' -%}
      {{ lookup('file', varsfile, errors='ignore') | from_yaml | default({}, true) }}
      {%- endif -%}

  ignore_errors: "{{ awx_ignore_errors | default(False) }}"  # noqa ignore-errors
  loop: "{{ lookup('file', awx_config_path + '/groups/groups.yml') | from_yaml }}"
  loop_control:
    label: "{{ item.name }}"
