---

- name: Get all variables file
  ansible.builtin.set_fact:
    host_var_files: "{{ lookup('fileglob', awx_config_path + '/hosts/variables/*.json', wantlist=True) }}"

- name: Loop over all hosts and create list of ones not present
  set_fact:
    awx_hosts_non_existing: >-
      {{ awx_hosts_non_existing | default([]) + [ item.name ] }}
  when:
    - awx_host_dns_check | bool
    - lookup('dig', item.name) == 'NXDOMAIN'
  loop: "{{ lookup('file', awx_config_path + '/hosts/hosts.yml') | from_yaml }}"
  loop_control:
    label: "{{ item.name }}"

- name: Create AWX hosts  # noqa jinja[spacing]
  awx.awx.host:
    controller_host: "{{ awx_url }}"
    controller_username: "{{ awx_username if awx_token is undefined else omit }}"
    controller_password: "{{ awx_password if awx_token is undefined else omit }}"
    controller_oauthtoken: "{{ awx_token | default(omit) }}"
    validate_certs: "{{ awx_verify_ssl }}"

    name: "{{ item.name }}"
    description: "{{ item.description | default(omit) }}"
    inventory: "{{ item.inventory }}"
    variables: >-
      {% set varsfile = awx_config_path + '/hosts/variables/' + item.name + '.json' %}
      {%- if host_var_files is search('/' + item.name + '.json') -%}
      {{ lookup('file', varsfile) }}
      {%- else -%}
      {}
      {%- endif -%}
  when:
    - awx_create_hosts | bool
    - not awx_host_dns_check | bool or ( awx_host_dns_check | bool and item.name not in awx_hosts_non_existing )
  loop: "{{ lookup('file', awx_config_path + '/hosts/hosts.yml') | from_yaml }}"
  loop_control:
     label: "{{ item.name }}"
