---

- name: Get all variables file
  ansible.builtin.set_fact:
    host_var_files: "{{ lookup('fileglob', awx_config_path + '/hosts/variables/*.json', wantlist=True) }}"

- name: Create AWX hosts  # noqa jinja[spacing]
  awx.awx.host:
    controller_host: "{{ awx_url }}"
    controller_username: "{{ awx_username if awx_token is undefined else omit }}"
    controller_password: "{{ awx_password if awx_token is undefined else omit }}"
    controller_oauthtoken: "{{ awx_token | default(omit) }}"
    validate_certs: "{{ awx_verify_ssl }}"

    name: "{{ item.name }}"
    description: "{{ item.description | default(omit) }}"
    inventory: "{{ item.inventory }}"
    variables: >-
      {% set varsfile = awx_config_path + '/hosts/variables/' + item.name + '.json' %}
      {%- if host_var_files is search('/' + item.name + '.json') -%}
      {{ lookup('file', varsfile) }}
      {%- else -%}
      {}
      {%- endif -%}

  # ignore_errors: yes
  loop: "{{ lookup('file', awx_config_path + '/hosts/hosts.yml') | from_yaml }}"
  loop_control:
    label:
      - "{{ item.name }}"
