---

- name: Get all variables file
  ansible.builtin.set_fact:
    inventory_source_var_files: "{{ lookup('fileglob', awx_config_path + '/inventory_sources/source_vars/*.json', wantlist=True) }}"

- name: Create AWX inventory sources  # noqa jinja[spacing]
  awx.awx.inventory_source:
    controller_host: "{{ awx_url }}"
    controller_username: "{{ awx_username if awx_token is undefined else omit }}"
    controller_password: "{{ awx_password if awx_token is undefined else omit }}"
    controller_oauthtoken: "{{ awx_token | default(omit) }}"
    validate_certs: "{{ awx_verify_ssl }}"

    name: "{{ item.name }}"
    inventory: "{{ item.inventory }}"
    organization: "{{ item.organization }}"
    description: "{{ item.description | default(omit) }}"

    credential: "{{ item.credential | default(omit) }}"
    custom_virtualenv: "{{ item.custom_virtualenv | default(omit) }}"
    enabled_value: "{{ item.enabled_value | default(omit) }}"
    enabled_var: "{{ item.enabled_var | default(omit) }}"
    execution_environment: "{{ item.execution_environment | default(omit) }}"
    host_filter: "{{ item.host_filter | default(omit) }}"
    overwrite: "{{ item.overwrite | default(omit) }}"
    overwrite_vars: "{{ item.overwrite_vars | default(omit) }}"
    source: "{{ item.source | default(omit) }}"
    source_path: "{{ item.source_path | default(omit) }}"
    source_project: "{{ item.source_project | default(omit) }}"
    source_vars: >-
      {% set varsfile = awx_config_path + '/inventory_sources/source_vars/' + item.name + '.json' %}
      {%- if inventory_source_var_files is search('/' + item.name + '.json') -%}
      {{ lookup('file', varsfile) }}
      {%- else -%}
      {}
      {%- endif -%}
    state: "{{ item.state | default(omit) }}"
    timeout: "{{ item.timeout | default(omit) }}"
    update_cache_timeout: "{{ item.update_cache_timeout | default(omit) }}"
    update_on_launch: "{{ item.update_on_launch | default(omit) }}"
    verbosity: "{{ item.verbosity | default(omit) }}"

  # ignore_errors: yes
  loop: "{{ lookup('file', awx_config_path + '/inventory_sources/inventory_sources.yml') | from_yaml }}"
  loop_control:
    label:
      - "{{ item.name }}"
