---

- name: Read all inventories from file
  ansible.builtin.set_fact:
    __awx_inventories: "{{ lookup('file', awx_config_path + '/inventory/inventory.yml') | from_yaml }}"

- name: Template variable files
  ansible.builtin.template:
    src: "{{ awx_config_path + '/inventory/variables/' + item.name + '.yml.j2' }}"
    dest: "{{ awx_config_path + '/inventory/variables/' + item.name + '.yml' }}"
    block_start_string: "<%"
    block_end_string: "%>"
    variable_start_string: "<="
    variable_end_string: "=>"
  changed_when: false
  failed_when: false
  loop: "{{ __awx_inventories }}"

- name: Create AWX inventories  # noqa jinja[spacing]
  awx.awx.inventory:

    # AWX connection & authentication
    controller_config_file: "{{ awx_config_file | default(omit) }}"
    controller_host: "{{ awx_url }}"
    controller_username: "{{ awx_username if awx_token is undefined else omit }}"
    controller_password: "{{ awx_password if awx_token is undefined else omit }}"
    controller_oauthtoken: "{{ awx_token | default(omit) }}"
    validate_certs: "{{ awx_verify_ssl }}"

    # Required parameters
    name: "{{ item.name }}"
    organization: "{{ item.organization }}"

    # Optional parameters
    copy_from: "{{ item.copy_from | default(omit) }}"
    description: "{{ item.description | default(omit) }}"
    host_filter: "{{ item.host_filter | default(omit) }}"
    input_inventories: "{{ item.input_inventories | default(omit) }}"
    instance_groups: "{{ item.instance_groups | default(omit) }}"
    kind: "{{ item.kind | default(omit) }}"
    new_name: "{{ item.new_name | default(omit) }}"
    prevent_instance_group_fallback: "{{ item.prevent_instance_group_fallback | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    variables: >-
      {%- if item.variables is defined -%}
        {{ item.variables }}
      {%- else -%}
        {%- set var_path = '/inventory/variables/' -%}
        {%- if awx_vars_format == 'json' -%}
          {%- set varsfile = awx_config_path + var_path + item.name + '.json' -%}
          {{ lookup('file', varsfile, errors='ignore') | default({}, true) }}
        {%- elif awx_vars_format == 'yaml' -%}
          {%- set varsfile = awx_config_path + var_path + item.name + '.yml' -%}
          {{ lookup('file', varsfile, errors='ignore') | from_yaml | default(omit, true) }}
        {%- endif -%}
      {%- endif -%}
  ignore_errors: "{{ awx_ignore_errors | default(False) }}"  # noqa ignore-errors
  loop: "{{ __awx_inventories }}"
  loop_control:
    label: "{{ item.name }}"
