---

- name: Get all variables file
  ansible.builtin.set_fact:
    job_template_var_files: "{{ lookup('fileglob', awx_config_path + '/job_templates/extra_vars/*.json', wantlist=True) }}"

- name: Create AWX job templates  # noqa ignore-errors jinja[spacing]
  awx.awx.job_template:
    controller_host: "{{ awx_url }}"
    controller_username: "{{ awx_username if awx_token is undefined else omit }}"
    controller_password: "{{ awx_password if awx_token is undefined else omit }}"
    controller_oauthtoken: "{{ awx_token | default(omit) }}"
    validate_certs: "{{ awx_verify_ssl }}"

    name: "{{ item.name }}"
    organization: "{{ item.organization }}"
    inventory: "{{ item.inventory }}"
    project: "{{ item.project }}"
    playbook: "{{ item.playbook }}"

    allow_simultaneous: "{{ item.allow_simultaneous | default(omit) }}"
    ask_credential_on_launch: "{{ item.ask_credential_on_launch | default(omit) }}"
    ask_diff_mode_on_launch: "{{ item.ask_diff_mode_on_launch | default(omit) }}"
    ask_inventory_on_launch: "{{ item.ask_inventory_on_launch | default(omit) }}"
    ask_job_type_on_launch: "{{ item.ask_job_type_on_launch | default(omit) }}"
    ask_limit_on_launch: "{{ item.ask_limit_on_launch | default(omit) }}"
    ask_scm_branch_on_launch: "{{ item.ask_scm_branch_on_launch | default(omit) }}"
    ask_skip_tags_on_launch: "{{ item.ask_skip_tags_on_launch | default(omit) }}"
    ask_tags_on_launch: "{{ item.ask_tags_on_launch | default(omit) }}"
    ask_variables_on_launch: "{{ item.ask_variables_on_launch | default(omit) }}"
    ask_verbosity_on_launch: "{{ item.ask_verbosity_on_launch | default(omit) }}"
    become_enabled: "{{ item.become_enabled | default(omit) }}"
    credentials: "{{ item.credentials | default(omit) }}"
    custom_virtualenv: "{{ item.custom_virtualenv | default(omit) }}"
    description: "{{ item.description | default(omit) }}"
    diff_mode: "{{ item.diff_mode | default(omit) }}"
    extra_vars: >-
      {% set varsfile = awx_config_path + '/job_templates/extra_vars/' + item.name + '.json' %}
      {%- if job_template_var_files is search('/' + item.name + '.json') -%}
      {{ lookup('file', varsfile) }}
      {%- else -%}
      {}
      {%- endif -%}
    force_handlers: "{{ item.force_handlers | default(omit) }}"
    forks: "{{ item.forks | default(omit) }}"
    host_config_key: "{{ item.host_config_key | default(omit) }}"
    job_slice_count: "{{ item.job_slice_count | default(omit) }}"
    job_tags: "{{ item.job_tags | default(omit) }}"
    job_type: "{{ item.job_type | default(omit) }}"
    limit: "{{ item.limit | default(omit) }}"
    # playbook: "{{ item.playbook | default(omit) }}"
    scm_branch: "{{ item.scm_branch | default(omit) }}"
    skip_tags: "{{ item.skip_tags | default(omit) }}"
    start_at_task: "{{ item.start_at_task | default(omit) }}"
    survey_enabled: "{{ item.survey_enabled | default(omit) }}"
    survey_spec: "{{ item.survey_spec | default(omit) }}"
    timeout: "{{ item.timeout | default(omit) }}"
    use_fact_cache: "{{ item.use_fact_cache | default(omit) }}"
    verbosity: "{{ item.verbosity | default(omit) }}"

  ignore_errors: "{{ ignore_errors | default(False) }}"
  loop: "{{ lookup('file', awx_config_path + '/job_templates/job_templates.yml') | from_yaml }}"
  loop_control:
    label:
      - "{{ item.name }}"
#  vars:
#    ansible_python_interpreter: "{{ venv_python }}"
  when:
    - item.inventory != None
    - item.project != None
