---

- name: Load job templates from file
  ansible.builtin.set_fact:
    __awx_job_templates: "{{ lookup('file', awx_config_path + '/job_templates/job_templates.yml') | from_yaml }}"

- name: Create AWX job_template  # noqa jinja[spacing]
  awx.awx.job_template:

    # AWX connection & authentication
    controller_config_file: "{{ awx_config_file | default(omit) }}"
    controller_host: "{{ awx_url }}"
    controller_username: "{{ awx_username if awx_token is undefined else omit }}"
    controller_password: "{{ awx_password if awx_token is undefined else omit }}"
    controller_oauthtoken: "{{ awx_token | default(omit) }}"
    validate_certs: "{{ awx_verify_ssl }}"

    # Required parameters
    name: "{{ item.name }}"
    organization: "{{ item.organization }}"
    inventory: "{{ item.inventory }}"
    project: "{{ item.project }}"
    playbook: "{{ item.playbook }}"

    # Optional parameters
    allow_simultaneous: "{{ item.allow_simultaneous | default(omit) }}"
    ask_credential_on_launch: "{{ item.ask_credential_on_launch | default(omit) }}"
    ask_diff_mode_on_launch: "{{ item.ask_diff_mode_on_launch | default(omit) }}"
    ask_execution_environment_on_launch: "{{ item.ask_execution_environment_on_launch | default(omit) }}"
    ask_forks_on_launch: "{{ item.ask_forks_on_launch | default(omit) }}"
    ask_instance_groups_on_launch: "{{ item.ask_instance_groups_on_launch | default(omit) }}"
    ask_inventory_on_launch: "{{ item.ask_inventory_on_launch | default(omit) }}"
    ask_job_slice_count_on_launch: "{{ item.ask_job_slice_count_on_launch | default(omit) }}"
    ask_job_type_on_launch: "{{ item.ask_job_type_on_launch | default(omit) }}"
    ask_labels_on_launch: "{{ item.ask_labels_on_launch | default(omit) }}"
    ask_limit_on_launch: "{{ item.ask_limit_on_launch | default(omit) }}"
    ask_scm_branch_on_launch: "{{ item.ask_scm_branch_on_launch | default(omit) }}"
    ask_skip_tags_on_launch: "{{ item.ask_skip_tags_on_launch | default(omit) }}"
    ask_tags_on_launch: "{{ item.ask_tags_on_launch | default(omit) }}"
    ask_timeout_on_launch: "{{ item.ask_timeout_on_launch | default(omit) }}"
    ask_variables_on_launch: "{{ item.ask_variables_on_launch | default(omit) }}"
    ask_verbosity_on_launch: "{{ item.ask_verbosity_on_launch | default(omit) }}"
    become_enabled: "{{ item.become_enabled | default(omit) }}"
    copy_from: "{{ item.copy_from | default(omit) }}"
    credential: "{{ item.credential | default(omit) }}"
    credentials: "{{ item.credentials | default(omit) }}"
    custom_virtualenv: "{{ item.custom_virtualenv | default(omit) }}"
    description: "{{ item.description | default(omit) }}"
    diff_mode: "{{ item.diff_mode | default(omit) }}"
    execution_environment: "{{ item.execution_environment | default(omit) }}"
    extra_vars: >-
      {%- if item.extra_vars is defined -%}
        {{ item.extra_vars }}
      {%- else -%}
        {%- set var_path = '/job_templates/extra_vars/' -%}
        {%- if awx_vars_format == 'json' -%}
          {%- set varsfile = awx_config_path + var_path + item.name + '.json' -%}
          {{ lookup('file', varsfile, errors='ignore') | default({}, true) }}
        {%- elif awx_vars_format == 'yaml' -%}
          {%- set template = awx_config_path + var_path + item.name + '.yml.j2' -%}
          {%- set varsfile = awx_config_path + var_path + item.name + '.yml' -%}
          {%- if template is is_file -%}
            {{ lookup('template', template) | from_yaml | default(omit, true) }}
          {%- else -%}
            {{ lookup('file', varsfile, errors='ignore') | from_yaml | default(omit, true) }}
          {%- endif -%}
        {%- endif -%}
      {%- endif -%}
    force_handlers: "{{ item.force_handlers | default(omit) }}"
    forks: "{{ item.forks | default(omit) }}"
    host_config_key: "{{ item.host_config_key | default(omit) }}"
    instance_groups: "{{ item.instance_groups | default(omit) }}"
    job_slice_count: "{{ item.job_slice_count | default(omit) }}"
    job_tags: "{{ item.job_tags | default(omit) }}"
    job_type: "{{ item.job_type | default(omit) }}"
    labels: "{{ item.labels | default(omit) }}"
    limit: "{{ item.limit | default(omit) }}"
    new_name: "{{ item.new_name | default(omit) }}"
    notification_templates_error: "{{ item.notification_templates_error | default(omit) }}"
    notification_templates_started: "{{ item.notification_templates_started | default(omit) }}"
    notification_templates_success: "{{ item.notification_templates_success | default(omit) }}"
    prevent_instance_group_fallback: "{{ item.prevent_instance_group_fallback | default(omit) }}"
    scm_branch: "{{ item.scm_branch | default(omit) }}"
    skip_tags: "{{ item.skip_tags | default(omit) }}"
    start_at_task: "{{ item.start_at_task | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    survey_enabled: "{{ item.survey_enabled | default(omit) }}"
    survey_spec: >-
      {%- if item.survey_spec is defined -%}
        {{ item.survey_spec }}
      {%- else -%}
        {%- set var_path = '/job_templates/survey_spec/' -%}
        {%- if awx_vars_format == 'json' -%}
          {%- set varsfile = awx_config_path + var_path + item.name + '.json' -%}
          {{ lookup('file', varsfile, errors='ignore') | default(omit, true) }}
        {%- elif awx_vars_format == 'yaml' -%}
          {%- set template = awx_config_path + var_path + item.name + '.yml.j2' -%}
          {%- set varsfile = awx_config_path + var_path + item.name + '.yml' -%}
          {%- if template is is_file -%}
            {{ lookup('template', template) | from_yaml | default(omit, true) }}
          {%- else -%}
            {{ lookup('file', varsfile, errors='ignore') | from_yaml | default(omit, true) }}
          {%- endif -%}
        {%- endif -%}
      {%- endif -%}
    timeout: "{{ item.timeout | default(omit) }}"
    use_fact_cache: "{{ item.use_fact_cache | default(omit) }}"
    vault_credential: "{{ item.vault_credential | default(omit) }}"
    verbosity: "{{ item.verbosity | default(omit) }}"
    webhook_credential: "{{ item.webhook_credential | default(omit) }}"
    webhook_service: "{{ item.webhook_service | default(omit) }}"

  ignore_errors: "{{ awx_ignore_errors | default(False) }}"  # noqa ignore-errors
  loop: "{{ __awx_job_templates }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - item.inventory != None
    - item.project != None

- name: Grant access to specific teams
  awx.awx.role:

    # AWX connection & authentication
    controller_config_file: "{{ awx_config_file | default(omit) }}"
    controller_host: "{{ awx_url }}"
    controller_username: "{{ awx_username if awx_token is undefined else omit }}"
    controller_password: "{{ awx_password if awx_token is undefined else omit }}"
    controller_oauthtoken: "{{ awx_token | default(omit) }}"
    validate_certs: "{{ awx_verify_ssl }}"

    team: "{{ item.1.name }}"
    role: "{{ item.1.role }}"
    job_templates:
      - "{{ item.0.name }}"
    state: "{{ item.1.state | default('present') }}"

  loop: >-
    {{
      __awx_job_templates
      | selectattr('roles', 'defined')
      | list
      | subelements('roles')
      | selectattr('1.type', 'defined')
      | selectattr('1.type', 'equalto', 'team')
      | list
    }}
  loop_control:
    label: "{{ item.0.name }} -> {{ item.1.name }}"

- name: Grant access to specific users
  awx.awx.role:

    # AWX connection & authentication
    controller_config_file: "{{ awx_config_file | default(omit) }}"
    controller_host: "{{ awx_url }}"
    controller_username: "{{ awx_username if awx_token is undefined else omit }}"
    controller_password: "{{ awx_password if awx_token is undefined else omit }}"
    controller_oauthtoken: "{{ awx_token | default(omit) }}"
    validate_certs: "{{ awx_verify_ssl }}"

    user: "{{ item.1.name }}"
    role: "{{ item.1.role }}"
    job_templates:
      - "{{ item.0.name }}"
    state: "{{ item.1.state | default('present') }}"

  loop: >-
    {{
      __awx_job_templates
      | selectattr('roles', 'defined')
      | list
      | subelements('roles')
      | selectattr('1.type', 'defined')
      | selectattr('1.type', 'equalto', 'user')
      | list
    }}
  loop_control:
    label: "{{ item.0.name }} -> {{ item.1.name }}"
