---

- name: Show settings
  ansible.builtin.debug:
    msg:
      awx_type: "{{ awx_type }}"
      awx_env: "{{ awx_env }}"
      awx_url: "{{ tower_awx[awx_type][awx_env]['url'] }}"

- name: Retrieve Oauth2 token
  ansible.builtin.include_tasks:
    file: token.yml

- name: Include import of all resources
  ansible.builtin.include_tasks:
    file: "{{ awx_resource }}.yml"
  loop: "{{ awx_resources_import }}"
  loop_control:
    loop_var: awx_resource
