---

- name: Create AWX notification_template
  awx.awx.notification_template:

    # AWX connection & authentication
    controller_config_file: "{{ awx_config_file | default(omit) }}"
    controller_host: "{{ awx_url }}"
    controller_username: "{{ awx_username if awx_token is undefined else omit }}"
    controller_password: "{{ awx_password if awx_token is undefined else omit }}"
    controller_oauthtoken: "{{ awx_token | default(omit) }}"
    validate_certs: "{{ awx_verify_ssl }}"

    # Required parameters
    name: "{{ item.name }}"

    # Optional parameters
    copy_from: "{{ item.copy_from | default(omit) }}"
    description: "{{ item.description | default(omit) }}"
    messages: "{{ item.messages | default(omit) }}"
    new_name: "{{ item.new_name | default(omit) }}"
    notification_configuration: "{{ item.notification_configuration | default(omit) }}"
    notification_type: "{{ item.notification_type | default(omit) }}"
    organization: "{{ item.organization | default(omit) }}"
    state: "{{ item.state | default(omit) }}"

  ignore_errors: "{{ awx_ignore_errors | default(False) }}"  # noqa ignore-errors
  loop: "{{ lookup('file', awx_config_path + '/notification_templates/notification_templates.yml') | from_yaml }}"
  loop_control:
    label: "{{ item.name }}"
