---

- name: Create AWX schedules
  awx.awx.notification_template:
    controller_host: "{{ tower_awx[awx_type][awx_env]['url'] }}"
    controller_username: "{{ tower_awx[awx_type][awx_env]['api_user'] if awx_token is undefined else omit }}"
    controller_password: "{{ tower_awx[awx_type][awx_env]['api_password'] if awx_token is undefined else omit }}"
    controller_oauthtoken: "{{ awx_token | default(omit) }}"
    validate_certs: "{{ tower_awx[awx_type][awx_env]['validate_certs'] }}"

    name: "{{ item.name }}"
    state: "{{ item.state | default(omit) }}"
    organization: "{{ item.organization }}"
    description: "{{ item.description | default(omit) }}"

    copy_from: "{{ item.copy_from | default(omit) }}"
    messages: "{{ item.messages | default(omit) }}"
    new_name: "{{ item.new_name | default(omit) }}"
    notification_configuration: "{{ item.notification_configuration | default(omit) }}"
    notification_type: "{{ item.notification_type | default(omit) }}"

  # ignore_errors: yes
  loop: "{{ lookup('file', awx_config_path + '/notification_templates/notification_templates.yml') | from_yaml }}"
  loop_control:
    label:
      - "{{ item.name }}"
