---

- name: Create AWX organizations  # noqa ignore-errors
  awx.awx.organization:
    controller_host: "{{ awx_url }}"
    controller_username: "{{ awx_username if awx_token is undefined else omit }}"
    controller_password: "{{ awx_password if awx_token is undefined else omit }}"
    controller_oauthtoken: "{{ awx_token | default(omit) }}"
    validate_certs: "{{ awx_verify_ssl }}"

    name: "{{ item.name }}"
    description: "{{ item.description }}"
    custom_virtualenv: "{{ item.custom_virtualenv | default(omit) }}"

  # ignore_errors: yes
  loop: "{{ lookup('file', awx_config_path + '/organizations/organizations.yml') | from_yaml }}"
  loop_control:
    label:
      - "{{ item.name }}"
