---

- name: Load projects from file
  ansible.builtin.set_fact:
    __awx_projects: "{{ lookup('file', awx_config_path + '/projects/projects.yml') | from_yaml }}"

- name: Create AWX project
  awx.awx.project:

    # AWX connection & authentication
    controller_config_file: "{{ awx_config_file | default(omit) }}"
    controller_host: "{{ awx_url }}"
    controller_username: "{{ awx_username if awx_token is undefined else omit }}"
    controller_password: "{{ awx_password if awx_token is undefined else omit }}"
    controller_oauthtoken: "{{ awx_token | default(omit) }}"
    validate_certs: "{{ awx_verify_ssl }}"

    # Required parameters
    name: "{{ item.name }}"
    organization: "{{ item.organization }}"

    # Optional parameters
    allow_override: "{{ item.allow_override | default(omit) }}"
    copy_from: "{{ item.copy_from | default(omit) }}"
    credential: "{{ item.credential | default(omit) }}"
    custom_virtualenv: "{{ item.custom_virtualenv | default(omit) }}"
    default_environment: "{{ item.default_environment | default(omit) }}"
    description: "{{ item.description | default(omit) }}"
    interval: "{{ item.interval | default(omit) }}"
    local_path: "{{ item.local_path | default(omit) }}"
    new_name: "{{ item.new_name | default(omit) }}"
    notification_templates_error: "{{ item.notification_templates_error | default(omit) }}"
    notification_templates_started: "{{ item.notification_templates_started | default(omit) }}"
    notification_templates_success: "{{ item.notification_templates_success | default(omit) }}"
    scm_branch: "{{ item.scm_branch | default(omit) }}"
    scm_clean: "{{ item.scm_clean | default(omit) }}"
    scm_delete_on_update: "{{ item.scm_delete_on_update | default(omit) }}"
    scm_refspec: "{{ item.scm_refspec | default(omit) }}"
    scm_track_submodules: "{{ item.scm_track_submodules | default(omit) }}"
    scm_type: "{{ item.scm_type | default('git') }}"
    scm_update_cache_timeout: "{{ item.scm_update_cache_timeout | default(omit) }}"
    scm_update_on_launch: "{{ item.scm_update_on_launch | default(omit) }}"
    scm_url: "{{ item.scm_url | default(omit) }}"
    signature_validation_credential: "{{ item.signature_validation_credential | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    timeout: "{{ item.timeout | default(omit) }}"
    # update_project: "{{ item.update_project | default(True) }}"
    wait: "{{ item.wait | default(True) }}"

  ignore_errors: "{{ awx_ignore_errors | default(False) }}"  # noqa ignore-errors
  loop: "{{ __awx_projects }}"
  loop_control:
    label: "{{ item.name }}"

- name: Force project update
  awx.awx.project_update:
    # AWX connection & authentication
    controller_config_file: "{{ awx_config_file | default(omit) }}"
    controller_host: "{{ awx_url }}"
    controller_username: "{{ awx_username if awx_token is undefined else omit }}"
    controller_password: "{{ awx_password if awx_token is undefined else omit }}"
    controller_oauthtoken: "{{ awx_token | default(omit) }}"
    validate_certs: "{{ awx_verify_ssl }}"

    project: "{{ item.name }}"

  loop: "{{ __awx_projects }}"
  loop_control:
    label: "{{ item.name }}"
  when: item.update_project is defined and item.update_project | bool

- name: Grant access to specific teams
  awx.awx.role:

    # AWX connection & authentication
    controller_config_file: "{{ awx_config_file | default(omit) }}"
    controller_host: "{{ awx_url }}"
    controller_username: "{{ awx_username if awx_token is undefined else omit }}"
    controller_password: "{{ awx_password if awx_token is undefined else omit }}"
    controller_oauthtoken: "{{ awx_token | default(omit) }}"
    validate_certs: "{{ awx_verify_ssl }}"

    team: "{{ item.1.name }}"
    role: "{{ item.1.role }}"
    projects:
      - "{{ item.0.name }}"
    state: "{{ item.1.state | default('present') }}"

  loop: >-
    {{
      __awx_projects
      | selectattr('roles', 'defined')
      | list
      | subelements('roles')
      | selectattr('1.type', 'defined')
      | selectattr('1.type', 'equalto', 'team')
      | list
    }}
  loop_control:
    label: "{{ item.0.name }} -> {{ item.1.name }}"

- name: Grant access to specific users
  awx.awx.role:

    # AWX connection & authentication
    controller_config_file: "{{ awx_config_file | default(omit) }}"
    controller_host: "{{ awx_url }}"
    controller_username: "{{ awx_username if awx_token is undefined else omit }}"
    controller_password: "{{ awx_password if awx_token is undefined else omit }}"
    controller_oauthtoken: "{{ awx_token | default(omit) }}"
    validate_certs: "{{ awx_verify_ssl }}"

    user: "{{ item.1.name }}"
    role: "{{ item.1.role }}"
    projects:
      - "{{ item.0.name }}"
    state: "{{ item.1.state | default('present') }}"

  loop: >-
    {{
      __awx_projects
      | selectattr('roles', 'defined')
      | list
      | subelements('roles')
      | selectattr('1.type', 'defined')
      | selectattr('1.type', 'equalto', 'user')
      | list
    }}
  loop_control:
    label: "{{ item.0.name }} -> {{ item.1.name }}"
