---

- name: Create AWX project  # noqa ignore-errors
  awx.awx.project:
    controller_host: "{{ awx_url }}"
    controller_username: "{{ awx_username if awx_token is undefined else omit }}"
    controller_password: "{{ awx_password if awx_token is undefined else omit }}"
    controller_oauthtoken: "{{ awx_token | default(omit) }}"
    validate_certs: "{{ awx_verify_ssl }}"

    name: "{{ item.name }}"
    organization: "{{ item.organization }}"

    scm_url: "{{ item.scm_url }}"
    scm_branch: "{{ item.scm_branch }}"
    scm_type: "{{ item.scm_type | default('git') }}"

    allow_override: "{{ item.allow_override | default(omit) }}"
    credential: "{{ item.credential if item.credential is defined and item.credential != None else omit }}"
    custom_virtualenv: "{{ item.custom_virtualenv if item.custom_virtualenv is defined and item.custom_virtualenv != None else omit }}"
    description: "{{ item.description | default(omit) }}"
    # scm_branch: "{{ item.scm_branch | default(omit) }}"
    scm_clean: "{{ item.scm_clean | default(omit) }}"
    scm_delete_on_update: "{{ item.scm_delete_on_update | default(omit) }}"
    scm_refspec: "{{ item.scm_refspec | default(omit) }}"
    # scm_type: "{{ item.scm_type | default(omit) }}"
    scm_update_cache_timeout: "{{ item.scm_update_cache_timeout | default(omit) }}"
    scm_update_on_launch: "{{ item.scm_update_on_launch | default(omit) }}"
    # scm_url: "{{ item.scm_url | default(omit) }}"
    timeout: "{{ item.timeout | default(omit) }}"
    update_project: "{{ item.update_project | default(True) }}"
    wait: "{{ item.wait | default(True) }}"
  ignore_errors: "{{ ignore_errors | default(False) }}"
  loop: "{{ lookup('file', awx_config_path + '/projects/projects.yml') | from_yaml }}"
  loop_control:
    label:
      - "{{ item.name }}"
