---

- name: Create AWX role
  awx.awx.role:

    # AWX connection & authentication
    controller_config_file: "{{ awx_config_file | default(omit) }}"
    controller_host: "{{ awx_url }}"
    controller_username: "{{ awx_username if awx_token is undefined else omit }}"
    controller_password: "{{ awx_password if awx_token is undefined else omit }}"
    controller_oauthtoken: "{{ awx_token | default(omit) }}"
    validate_certs: "{{ awx_verify_ssl }}"

    # Required parameters
    role: "{{ item.role }}"

    # Optional parameters
    credential: "{{ item.credential | default(omit) }}"
    credentials: "{{ item.credentials | default(omit) }}"
    instance_groups: "{{ item.instance_groups | default(omit) }}"
    inventories: "{{ item.inventories | default(omit) }}"
    inventory: "{{ item.inventory | default(omit) }}"
    job_template: "{{ item.job_template | default(omit) }}"
    job_templates: "{{ item.job_templates | default(omit) }}"
    lookup_organization: "{{ item.lookup_organization | default(omit) }}"
    organization: "{{ item.organization | default(omit) }}"
    organizations: "{{ item.organizations | default(omit) }}"
    project: "{{ item.project | default(omit) }}"
    projects: "{{ item.projects | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    target_team: "{{ item.target_team | default(omit) }}"
    target_teams: "{{ item.target_teams | default(omit) }}"
    team: "{{ item.team | default(omit) }}"
    user: "{{ item.user | default(omit) }}"
    workflow: "{{ item.workflow | default(omit) }}"
    workflows: "{{ item.workflows | default(omit) }}"

  ignore_errors: "{{ awx_ignore_errors | default(False) }}"  # noqa ignore-errors
  loop: "{{ lookup('file', awx_config_path + '/roles/roles.yml') | from_yaml }}"
  loop_control:
    label: "{{ item.name }}"
