---

- name: Create AWX schedules
  awx.awx.schedule:
    controller_host: "{{ awx_url }}"
    controller_username: "{{ awx_username if awx_token is undefined else omit }}"
    controller_password: "{{ awx_password if awx_token is undefined else omit }}"
    controller_oauthtoken: "{{ awx_token | default(omit) }}"
    validate_certs: "{{ awx_verify_ssl }}"

    name: "{{ item.name }}"
    state: "{{ item.state | default(omit) }}"
    organization: "{{ item.organization | default(omit) }}"
    description: "{{ item.description | default(omit) }}"

    credentials: "{{ item.credentials | default(omit) }}"
    diff_mode: "{{ item.diff_mode | default(omit) }}"
    enabled: "{{ item.enabled | default(omit) }}"
    extra_data: "{{ item.extra_data | default(omit) }}"
    inventory: "{{ item.inventory | default(omit) }}"
    job_tags: "{{ item.job_tags | default(omit) }}"
    job_type: "{{ item.job_type | default(omit) }}"
    limit: "{{ item.limit | default(omit) }}"
    new_name: "{{ item.new_name | default(omit) }}"
    rrule: "{{ item.rrule | default(omit) }}"
    scm_branch: "{{ item.scm_branch | default(omit) }}"
    skip_tags: "{{ item.skip_tags | default(omit) }}"
    unified_job_template: "{{ item.unified_job_template | default(omit) }}"
    verbosity: "{{ item.verbosity | default(omit) }}"

  # ignore_errors: yes
  loop: "{{ lookup('file', awx_config_path + '/schedules/schedules.yml') | from_yaml }}"
  loop_control:
    label:
      - "{{ item.name }}"
