---

- name: Create AWX teams  # noqa ignore-errors
  awx.awx.team:
    controller_host: "{{ awx_url }}"
    controller_username: "{{ awx_username if awx_token is undefined else omit }}"
    controller_password: "{{ awx_password if awx_token is undefined else omit }}"
    controller_oauthtoken: "{{ awx_token | default(omit) }}"
    validate_certs: "{{ awx_verify_ssl }}"

    name: "{{ item.name }}"
    description: "{{ item.description }}"
    organization: "{{ item.organization }}"

  # ignore_errors: yes
  loop: "{{ lookup('file', awx_config_path + '/teams/teams.yml') | from_yaml }}"
  loop_control:
    label:
      - "{{ item.name }}"
