---

- name: Create AWX team
  awx.awx.team:

    # AWX connection & authentication
    controller_config_file: "{{ awx_config_file | default(omit) }}"
    controller_host: "{{ awx_url }}"
    controller_username: "{{ awx_username if awx_token is undefined else omit }}"
    controller_password: "{{ awx_password if awx_token is undefined else omit }}"
    controller_oauthtoken: "{{ awx_token | default(omit) }}"
    validate_certs: "{{ awx_verify_ssl }}"

    # Required parameters
    name: "{{ item.name }}"
    organization: "{{ item.organization }}"

    # Optional parameters
    description: "{{ item.description | default(omit) }}"
    new_name: "{{ item.new_name | default(omit) }}"
    state: "{{ item.state | default(omit) }}"

  ignore_errors: "{{ ignore_errors | default(False) }}"  # noqa ignore-errors
  loop: "{{ lookup('file', awx_config_path + '/teams/teams.yml') | from_yaml }}"
  loop_control:
    label: "{{ item.name }}"
