---

- name: Retrieve Oauth2 token
  awx.awx.token:
    # AWX connection & authentication
    controller_config_file: "{{ awx_config_file | default(omit) }}"
    controller_host: "{{ awx_url }}"
    controller_username: "{{ awx_username if awx_token is undefined else omit }}"
    controller_password: "{{ awx_password if awx_token is undefined else omit }}"
    controller_oauthtoken: "{{ awx_token | default(omit) }}"
    validate_certs: "{{ awx_verify_ssl }}"

    scope: "write"
    state: present

- name: Save token
  ansible.builtin.set_fact:
    awx_token: "{{ controller_token.token }}"
