---

- name: Create AWX schedules
  awx.awx.workflow_job_template:
    controller_host: "{{ awx_url }}"
    controller_username: "{{ awx_username if awx_token is undefined else omit }}"
    controller_password: "{{ awx_password if awx_token is undefined else omit }}"
    controller_oauthtoken: "{{ awx_token | default(omit) }}"
    validate_certs: "{{ awx_verify_ssl }}"

    name: "{{ item.name }}"
    state: "{{ item.state | default(omit) }}"
    organization: "{{ item.organization }}"
    description: "{{ item.description | default(omit) }}"

    allow_simultaneous: "{{ item.allow_simultaneous | default(omit) }}"
    ask_inventory_on_launch: "{{ item.ask_inventory_on_launch | default(omit) }}"
    ask_limit_on_launch: "{{ item.ask_limit_on_launch | default(omit) }}"
    ask_scm_branch_on_launch: "{{ item.ask_scm_branch_on_launch | default(omit) }}"
    ask_variables_on_launch: "{{ item.ask_variables_on_launch | default(omit) }}"
    copy_from: "{{ item.copy_from | default(omit) }}"
    destroy_current_schema: "{{ item.destroy_current_schema | default(omit) }}"
    extra_vars: "{{ item.extra_vars | default(omit) }}"
    inventory: "{{ item.inventory | default(omit) }}"
    labels: "{{ item.labels | default(omit) }}"
    limit: "{{ item.limit | default(omit) }}"
    new_name: "{{ item.new_name | default(omit) }}"
    notification_templates_approvals: "{{ item.notification_templates_approvals | default(omit) }}"
    notification_templates_error: "{{ item.notification_templates_error | default(omit) }}"
    notification_templates_started: "{{ item.notification_templates_started | default(omit) }}"
    notification_templates_success: "{{ item.notification_templates_success | default(omit) }}"
    schema: "{{ item.schema | default(omit) }}"
    scm_branch: "{{ item.scm_branch | default(omit) }}"
    survey_enabled: "{{ item.survey_enabled | default(omit) }}"
    survey_spec: "{{ item.survey_spec | default(omit) }}"
    webhook_credential: "{{ item.webhook_credential | default(omit) }}"
    webhook_service: "{{ item.webhook_service | default(omit) }}"

  # ignore_errors: yes
  loop: "{{ lookup('file', awx_config_path + '/workflow_job_templates/workflow_job_templates.yml') | from_yaml }}"
  loop_control:
    label:
      - "{{ item.name }}"
