---

- name: Load workflow job templates from file
  ansible.builtin.set_fact:
    __awx_workflow_job_templates: "{{ lookup('file', awx_config_path + '/workflow_job_templates/workflow_job_templates.yml') | from_yaml }}"

- name: Delete workflow_job_templates due to recreation
  awx.awx.workflow_job_template:
    # AWX connection & authentication
    controller_config_file: "{{ awx_config_file | default(omit) }}"
    controller_host: "{{ awx_url }}"
    controller_username: "{{ awx_username if awx_token is undefined else omit }}"
    controller_password: "{{ awx_password if awx_token is undefined else omit }}"
    controller_oauthtoken: "{{ awx_token | default(omit) }}"
    validate_certs: "{{ awx_verify_ssl }}"

    name: "{{ item.name }}"
    state: absent

  when:
    - (item.state | default('present')) == 'present'
    - awx_workflow_job_template_recreate | default(false) | bool
  ignore_errors: "{{ awx_ignore_errors | default(False) }}"  # noqa ignore-errors
  loop: "{{ __awx_workflow_job_templates }}"
  loop_control:
    label: "{{ item.name }}"

- name: Wait for 60 seconds
  ansible.builtin.pause:
    seconds: 60
  when:
    - awx_workflow_job_template_recreate | default(false) | bool

- name: Create AWX workflow_job_template  # noqa jinja[spacing]
  awx.awx.workflow_job_template:

    # AWX connection & authentication
    controller_config_file: "{{ awx_config_file | default(omit) }}"
    controller_host: "{{ awx_url }}"
    controller_username: "{{ awx_username if awx_token is undefined else omit }}"
    controller_password: "{{ awx_password if awx_token is undefined else omit }}"
    controller_oauthtoken: "{{ awx_token | default(omit) }}"
    validate_certs: "{{ awx_verify_ssl }}"

    # Required parameters
    name: "{{ item.name }}"

    # Optional parameters
    allow_simultaneous: "{{ item.allow_simultaneous | default(omit) }}"
    ask_inventory_on_launch: "{{ item.ask_inventory_on_launch | default(omit) }}"
    ask_labels_on_launch: "{{ item.ask_labels_on_launch | default(omit) }}"
    ask_limit_on_launch: "{{ item.ask_limit_on_launch | default(omit) }}"
    ask_scm_branch_on_launch: "{{ item.ask_scm_branch_on_launch | default(omit) }}"
    ask_skip_tags_on_launch: "{{ item.ask_skip_tags_on_launch | default(omit) }}"
    ask_tags_on_launch: "{{ item.ask_tags_on_launch | default(omit) }}"
    ask_variables_on_launch: "{{ item.ask_variables_on_launch | default(omit) }}"
    copy_from: "{{ item.copy_from | default(omit) }}"
    description: "{{ item.description | default(omit) }}"
    destroy_current_nodes: "{{ item.destroy_current_nodes | default(omit) }}"
    extra_vars: >-
      {%- if item.extra_vars is defined -%}
        {{ item.extra_vars }}
      {%- else -%}
        {%- set var_path = '/workflow_job_templates/extra_vars/' -%}
        {%- if awx_vars_format == 'json' -%}
          {%- set varsfile = awx_config_path + var_path + item.name + '.json' -%}
          {{ lookup('file', varsfile, errors='ignore') | default({}, true) }}
        {%- elif awx_vars_format == 'yaml' -%}
          {%- set template = awx_config_path + var_path + item.name + '.yml.j2' -%}
          {%- set varsfile = awx_config_path + var_path + item.name + '.yml' -%}
          {%- if template is is_file -%}
            {{ lookup('template', template) | from_yaml | default(omit, true) }}
          {%- else -%}
            {{ lookup('file', varsfile, errors='ignore') | from_yaml | default(omit, true) }}
          {%- endif -%}
        {%- endif -%}
      {%- endif -%}
    inventory: "{{ item.inventory | default(omit) }}"
    job_tags: "{{ item.job_tags | default(omit) }}"
    labels: "{{ item.labels | default(omit) }}"
    limit: "{{ item.limit | default(omit) }}"
    new_name: "{{ item.new_name | default(omit) }}"
    notification_templates_approvals: "{{ item.notification_templates_approvals | default(omit) }}"
    notification_templates_error: "{{ item.notification_templates_error | default(omit) }}"
    notification_templates_started: "{{ item.notification_templates_started | default(omit) }}"
    notification_templates_success: "{{ item.notification_templates_success | default(omit) }}"
    organization: "{{ item.organization | default(omit) }}"
    scm_branch: "{{ item.scm_branch | default(omit) }}"
    skip_tags: "{{ item.skip_tags | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    survey_enabled: "{{ item.survey_enabled | default(omit) }}"
    survey_spec: >-
      {%- if item.survey_spec is defined -%}
        {{ item.survey_spec }}
      {%- else -%}
        {%- set var_path = '/workflow_job_templates/survey_spec/' -%}
        {%- if awx_vars_format == 'json' -%}
          {%- set varsfile = awx_config_path + var_path + item.name + '.json' -%}
          {{ lookup('file', varsfile, errors='ignore') | default(omit, true) }}
        {%- elif awx_vars_format == 'yaml' -%}
          {%- set template = awx_config_path + var_path + item.name + '.yml.j2' -%}
          {%- set varsfile = awx_config_path + var_path + item.name + '.yml' -%}
          {%- if template is is_file -%}
            {{ lookup('template', template) | from_yaml | default(omit, true) }}
          {%- else -%}
            {{ lookup('file', varsfile, errors='ignore') | from_yaml | default(omit, true) }}
          {%- endif -%}
        {%- endif -%}
      {%- endif -%}
    webhook_credential: "{{ item.webhook_credential | default(omit) }}"
    webhook_service: "{{ item.webhook_service | default(omit) }}"
    workflow_nodes: >-
      {%- if item.workflow_nodes is defined -%}
        {{ item.workflow_nodes }}
      {%- else -%}
        {%- set var_path = '/workflow_job_templates/workflow_nodes/' -%}
        {%- if awx_vars_format == 'json' -%}
          {%- set varsfile = awx_config_path + var_path + item.name + '.json' -%}
          {{ lookup('file', varsfile, errors='ignore') | default(omit, true) }}
        {%- elif awx_vars_format == 'yaml' -%}
          {%- set template = awx_config_path + var_path + item.name + '.yml.j2' -%}
          {%- set varsfile = awx_config_path + var_path + item.name + '.yml' -%}
          {%- if template is is_file -%}
            {{ lookup('template', template) | from_yaml | default(omit, true) }}
          {%- else -%}
            {{ lookup('file', varsfile, errors='ignore') | from_yaml | default(omit, true) }}
          {%- endif -%}
        {%- endif -%}
      {%- endif -%}
  ignore_errors: "{{ awx_ignore_errors | default(False) }}"  # noqa ignore-errors
  loop: "{{ __awx_workflow_job_templates }}"
  loop_control:
    label: "{{ item.name }}"

- name: Grant access to specific teams
  awx.awx.role:

    # AWX connection & authentication
    controller_config_file: "{{ awx_config_file | default(omit) }}"
    controller_host: "{{ awx_url }}"
    controller_username: "{{ awx_username if awx_token is undefined else omit }}"
    controller_password: "{{ awx_password if awx_token is undefined else omit }}"
    controller_oauthtoken: "{{ awx_token | default(omit) }}"
    validate_certs: "{{ awx_verify_ssl }}"

    team: "{{ item.1.name }}"
    role: "{{ item.1.role }}"
    workflows:
      - "{{ item.0.name }}"
    state: "{{ item.1.state | default('present') }}"

  loop: >-
    {{
      __awx_workflow_job_templates
      | selectattr('roles', 'defined')
      | list
      | subelements('roles')
      | selectattr('1.type', 'defined')
      | selectattr('1.type', 'equalto', 'team')
      | list
    }}
  loop_control:
    label: "{{ item.0.name }} -> {{ item.1.name }}"

- name: Grant access to specific users
  awx.awx.role:

    # AWX connection & authentication
    controller_config_file: "{{ awx_config_file | default(omit) }}"
    controller_host: "{{ awx_url }}"
    controller_username: "{{ awx_username if awx_token is undefined else omit }}"
    controller_password: "{{ awx_password if awx_token is undefined else omit }}"
    controller_oauthtoken: "{{ awx_token | default(omit) }}"
    validate_certs: "{{ awx_verify_ssl }}"

    user: "{{ item.1.name }}"
    role: "{{ item.1.role }}"
    workflows:
      - "{{ item.0.name }}"
    state: "{{ item.1.state | default('present') }}"

  loop: >-
    {{
      __awx_workflow_job_templates
      | selectattr('roles', 'defined')
      | list
      | subelements('roles')
      | selectattr('1.type', 'defined')
      | selectattr('1.type', 'equalto', 'user')
      | list
    }}
  loop_control:
    label: "{{ item.0.name }} -> {{ item.1.name }}"
